parameters: {}
environment: {}
packages:
    - name: ftc-award-script
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: get
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          parameters: {}
          annotations: {}
          limits: {}
        - name: post
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          parameters: {}
          annotations: {}
          limits: {}
