parameters: {}
environment: {}
packages:
    - name: ftc-award-script
      shared: false
      envs:
        - key: POST_ENDPOINT
          scope: RUN_TIME
          value: https://dolphin-app-8el9v.ondigitalocean.app/ftc-award-script/post
        - key: OPENAI_API_KEY
          scope: RUN_TIME
          type: SECRET
          value: EV[1:ujX6WVMh+iBW8PCZwCcM56Hzct2js9Jg:QBsNlwvhO0nesmrx/QEbjk2Y9TCqfTcXZArgOLODapZM9yrdu2xm4QCkJ1CsSg2zSrqZFSaHCEbPFVNiXU/a6Tx2TQ==]
      parameters: {}
      annotations: {}
      functions:
        - name: get
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          parameters: {}
          annotations: {}
          limits: {}
        - name: post
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          parameters: {}
          annotations: {}
          limits: {}
