alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: ftc-award-script
    match:
      path:
        prefix: /
name: ftc-award-script
region: nyc
services:
- environment_slug: node-js
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:O6HSLCnRhe/+2voztzkoQsrsWNBClK1A:l/39rbaqwmo1QIO/xioEEFbITzPDZkhXvpgNJ8Kljrxwvhnez8ItJZOaU7ZrX2OlIyWBgxJHkW7Hgv09CCZQQs14Pg==]
  github:
    branch: main
    deploy_on_push: true
    repo: jschool504/ftc-award-script
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: ftc-award-script
  run_command: npm start
  source_dir: /
